[tools.eza]
version = "latest"
enabled = true

[tools.fd]
version = "latest"
enabled = true

[tools.fzf]
version = "latest"
enabled = true

[tools.rg]
version = "latest"
enabled = true

[tools.starship]
version = "latest"
enabled = true

[tools.zoxide]
version = "latest"
enabled = true

[tools.terraform]
version = "latest"
enabled = true

